### ISSUE TITLE
License

### ISSUE THREAD

**Issue by njern** [mlbright/forecast#7]
Hi there and nice work! Just wondering what kind of license this is under? Could you add one?

**Comment by mlbright** [comment]
Thanks! I chose the MIT license, but added it to the new [DarkSky](https://github.com/mlbright/darksky) repo, because this repo is now officially deprecated. See https://github.com/mlbright/forecast/pull/14.

**Comment by mlbright** [comment]
Hold your horses! This repo is not deprecated! You can rename GitHub repos. I did not know this, and so this repo is alive again.
